# Generated by Django 4.1 on 2022-09-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freddit', '0002_thread_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
    ]
