# Generated by Django 4.1 on 2022-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freddit', '0003_remove_comment_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=18),
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.CharField(default='Anonymous', max_length=18),
        ),
    ]
